[package]
name = "imgdist"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
anyhow = "1.0.95"
chrono = "0.4.39"
clap = { version = "4.5.23", features = ["derive"] }
flexi_logger = "0.29.8"
kamadak-exif = "0.6.1"
log = "0.4.22"
walkdir = "2.5.0"
